remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: NWinfo
description: Hardware information utility for Windows
show_downloads: true
github:
  zip_url: https://github.com/a1ive/nwinfo/releases/latest/download/nwinfo.zip
